---
- name: Create Glance database
  community.mysql.mysql_db:
    login_user: root
    login_unix_socket: "{{ glance_db_conf.mariadb_socket_path }}"
    name: "{{ glance_db_conf.db_name }}"
    state: present

- name: Create Glance db_user
  community.mysql.mysql_user:
    login_user: root
    login_unix_socket: "{{ glance_db_conf.mariadb_socket_path }}"
    name: "{{ glance_db_conf.db_user_name }}"
    password: "{{ glance_db_conf.db_user_password }}"
    state: present
    priv: "{{ glance_db_conf.db_name }}.*:ALL"
    host: "{{ item }}"
  loop:
    - "localhost"
    - "%"
