# SPDX-License-Identifier: MIT-0
---
# tasks file for roles/glance
- name: Check if the tasks has been running
  when: "'glance_servers' in group_names"
  block:
    - name: Ensure Mark Directory Exists
      ansible.builtin.file:
        path: "{{ glance_mark_dir_path }}"
        state: directory
        mode: '0755'

    - name: Check if glance tasks have been run
      ansible.builtin.stat:
        name: "{{ glance_mark_files_path.success }}"
      register: glance_mark_file

    - name: Skip if glance tasks have been run
      ansible.builtin.meta: end_role
      when: glance_mark_file.stat.exists

- name: Create Glance database and user
  ansible.builtin.import_tasks: create_glance_db.yml
  tags:
    - install
    - create_glance_db_and_db_user
  when: "'glance_servers' in group_names"

- name: Create Glance's service user,role,endpoints,and project
  ansible.builtin.import_tasks: create_galnce_service.yml
  tags:
    - install
    - create_glance_service_user_role_endpoints_and_project
  when: "'glance_servers' in group_names"

- name: Install Glance Packages
  ansible.builtin.import_tasks: install_packages.yml
  tags:
    - install
  when: "'glance_servers' in group_names"

- name: Deploy Glance Configuration File
  ansible.builtin.import_tasks: deploy_glance_conf_file.yml
  tags:
    - install
    - configure_glance
  when: "'glance_servers' in group_names"

- name: Sync Glance Database
  ansible.builtin.import_tasks: sync_glance_db.yml
  tags:
    - install
    - sync_glance_db
  when: "'glance_servers' in group_names"

- name: Ensure glance-api is restarted to apply Glance changes
  ansible.builtin.import_tasks: ensure_glance_service_running.yml
  tags:
    - install
    - ensure_glance_api_running
  when: "'glance_servers' in group_names"

- name: Create mark file to indicate glance tasks have been run
  ansible.builtin.file:
    path: "{{ glance_mark_files_path.success }}"
    state: touch
    mode: '0644'
  when: "'glance_servers' in group_names"
