# SPDX-License-Identifier: MIT-0
---
# tasks file for roles/db_install
- name: Check if the tasks has been running
  block:
    - name: Ensure Mark Directory Exists
      ansible.builtin.file:
        path: "{{ db_install_mark_dir_path }}"
        state: directory
        mode: '0755'

    - name: Check if db_install tasks have been run
      ansible.builtin.stat:
        name: "{{ db_install_mark_file_path }}"
      register: db_install_mark_file

    - name: Skip if db_install tasks have been run
      ansible.builtin.meta: end_role
      when: db_install_mark_file.stat.exists

- name: Install necessary database packages
  ansible.builtin.import_tasks: install_packages.yml
  tags:
    - install
  when: "'db_servers' in group_names"

- name: Configure OpenStack database configuration files
  ansible.builtin.import_tasks: configure_openstack_db_conf_file.yml
  tags:
    - install
    - config_db_conf_file
  when: "'db_servers' in group_names"

- name: Ensure database service is started and enabled
  ansible.builtin.import_tasks: ensure_service_running.yml
  tags:
    - install
    - ensure_db_service_running
  when: "'db_servers' in group_names"

- name: Init database
  ansible.builtin.import_tasks: init_db.yml
  tags:
    - install
    - init_db
  when: "'db_servers' in group_names"

- name: Create mark file to indicate db_install tasks have been run
  ansible.builtin.file:
    path: "{{ db_install_mark_file_path }}"
    state: touch
    mode: '0644'
  when: "'db_servers' in group_names"
