---
- name: Gather OS Information
  hosts: all
  tasks:
    - name: Gather OS information
      ansible.builtin.setup:
        gather_subset:
          - os_family
          - distribution
          - distribution_version
          - architecture

    - name: Display OS information
      ansible.builtin.debug:
        msg:
          - "OS Family: {{ ansible_facts['os_family'] }}"
          - "Distribution: {{ ansible_facts['distribution'] }}"
          - "Distribution Version: {{ ansible_facts['distribution_version'] }}"
          - "Architecture: {{ ansible_facts['architecture'] }}"
