# SPDX-License-Identifier: MIT-0
---
# tasks file for roles/rabbitmq
- name: Check if the tasks has been running
  when: "'rabbitmq_servers' in group_names"
  block:
    - name: Ensure Mark Directory Exists
      ansible.builtin.file:
        path: "{{ rabbitmq_mark_dir_path }}"
        state: directory
        mode: '0755'

    - name: Check if rabbitmq tasks have been run
      ansible.builtin.stat:
        name: "{{ rabbitmq_mark_file_path }}"
      register: rabbitmq_mark_file

    - name: Skip if rabbitmq tasks have been run
      ansible.builtin.meta: end_role
      when: rabbitmq_mark_file.stat.exists

# 必须要提前说明的是，官方仓库里面的RabbitMQ很抽象，是RabbitMQ-3.8的版本与配套的erlang，实际下载的是RabbitMQ-3.9
# 很有意思的是，3.9在CentOS-9-stream上不行，Controller与Compute节点上会出Nova各个组件无法与RabbitMQ连接的问题，Compute上面也是的
# 会出现以下报错
# 2025-10-22 01:29:46.687 4945 ERROR nova     self.connection.drain_events(timeout=timeout)
# 2025-10-22 01:29:46.687 4945 ERROR nova   File "/usr/lib/python3.9/site-packages/amqp/connection.py", line 522, in drain_events
# 2025-10-22 01:29:46.687 4945 ERROR nova     while not self.blocking_read(timeout):
# 2025-10-22 01:29:46.687 4945 ERROR nova   File "/usr/lib/python3.9/site-packages/amqp/connection.py", line 527, in blocking_read
# 2025-10-22 01:29:46.687 4945 ERROR nova     frame = self.transport.read_frame()
# 2025-10-22 01:29:46.687 4945 ERROR nova   File "/usr/lib/python3.9/site-packages/amqp/transport.py", line 310, in read_frame
# 2025-10-22 01:29:46.687 4945 ERROR nova     frame_header = read(7, True)
# 2025-10-22 01:29:46.687 4945 ERROR nova   File "/usr/lib/python3.9/site-packages/amqp/transport.py", line 647, in _read
# 2025-10-22 01:29:46.687 4945 ERROR nova     raise OSError('Server unexpectedly closed connection')
# 2025-10-22 01:29:46.687 4945 ERROR nova OSError: Server unexpectedly closed connection
# 2025-10-22 01:29:46.687 4945 ERROR nova
# 2025-10-22 01:29:49.861 4991 INFO os_vif [-] Loaded VIF plugins: linux_bridge, noop, ovs
# 2025-10-22 01:29:50.061 4991 CRITICAL nova [None req-67e49c93-2a04-4247-a081-5a1de8083d5f - - - - - -]
#  Unhandled error: OSError: Server unexpectedly closed connection
# 2025-10-22 01:29:50.061 4991 ERROR nova Traceback (most recent call last):
# 2025-10-22 01:29:50.061 4991 ERROR nova   File "/usr/lib/python3.9/site-packages/amqp/connection.py", line 511, in channel
# 2025-10-22 01:29:50.061 4991 ERROR nova     return self.channels[channel_id]
# 2025-10-22 01:29:50.061 4991 ERROR nova KeyError: None
# 2025-10-22 01:29:50.061 4991 ERROR nova
# 2025-10-22 01:29:50.061 4991 ERROR nova During handling of the above exception, another exception occurred:
# 2025-10-22 01:29:50.061 4991 ERROR nova
# 解决方法也很简单（？）从RabbitMQ官方下载最新版的RabbitMQ即可，应该是4.x版本的样子

- name: Insert IP and Short Hostname Mapping into /etc/hosts
  ansible.builtin.import_tasks: insert_rabbitmq_short_hostname.yml
  tags:
    - install
    - configure_hosts
  when: "'rabbitmq_servers' in group_names"

- name: Configure RabbitMQ Repository and GPG Keys
  ansible.builtin.import_tasks: configure_repository.yml
  tags:
    - install
    - configure_rabbitmq_repository
  when: "'rabbitmq_servers' in group_names"

- name: Install RabbitMQ Packages
  ansible.builtin.import_tasks: install_packages.yml
  tags:
    - install
  when:
    - "'rabbitmq_servers' in group_names"
    - ansible_facts['os_family'] == "RedHat"

- name: Ensure RabbitMQ Service is started and enabled
  ansible.builtin.import_tasks: ensure_service_running.yml
  tags:
    - install
    - ensure_rabbitmq_service_running
  when: "'rabbitmq_servers' in group_names"

- name: Enable RabbitMQ Management Plugin
  ansible.builtin.import_tasks: enable_rabbitmq_plugin.yml
  tags:
    - install
    - enable_rabbitmq_management_plugin
  when: "'rabbitmq_servers' in group_names"

- name: Configure RabbitMQ Users and Permissions
  ansible.builtin.import_tasks: configure_rabbitmq_openstack_users.yml
  tags:
    - install
    - configure_rabbitmq_users
  when: "'rabbitmq_servers' in group_names"

- name: Create mark file to indicate rabbitmq tasks have been run
  ansible.builtin.file:
    path: "{{ rabbitmq_mark_file_path }}"
    state: touch
    mode: '0644'
  when: "'rabbitmq_servers' in group_names"
