# SPDX-License-Identifier: MIT-0
---
# tasks file for roles/placement
- name: Check if the tasks has been running
  block:
    - name: Ensure Mark Directory Exists
      ansible.builtin.file:
        path: "{{ placement_mark_dir_path }}"
        state: directory
        mode: '0755'

    - name: Check if placement tasks have been run
      ansible.builtin.stat:
        name: "{{ placement_mark_files_path.success }}"
      register: placement_success_mark_file

    - name: Skip if placement tasks have been run
      ansible.builtin.meta: end_role
      when: placement_success_mark_file.stat.exists

- name: Create mark file to indicate placement tasks have been run
  ansible.builtin.file:
    path: "{{ placement_mark_files_path.success }}"
    state: touch
    mode: '0644'
