---
- name: Create OpenStack use pools
  when: "'ceph_bootstrap' in group_names"
  block:
    - name: Create OpenStack use pool
      ceph.automation.ceph_pool:
        name: "{{ item.name }}"
        pg_num: "{{ item.pg_num }}"
        pgp_num: "{{ item.pgp_num }}"
        state: present
      loop: "{{ ceph_openstack_pools }}"
      tags: create_openstack_pools

- name: 显式启用 rbd application
  command: ceph osd pool application enable {{ item.name }} rbd
  changed_when: false
  failed_when: false
  loop: "{{ ceph_openstack_pools }}"