---
- name: Ensure Ceph conf dir exists
  ansible.builtin.file:
    path: "{{ ceph_keyring_dir }}"
    state: directory
    mode: '0755'

- name: Deploy Ceph auth keys for OpenStack services for controller node
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0600'
  loop:
    - { src: "{{ ceph_local_files_dest_path.cinder_keyring }}", dest: "{{ ceph_keyring_file_path.cinder }}" }
    - { src: "{{ ceph_local_files_dest_path.ceph_conf }}", dest: "{{ ceph_conf_file }}" }
    - { src: "{{ ceph_local_files_dest_path.glance_keyring }}", dest: "{{ ceph_keyring_file_path.cinder_glance }}" }
  when: "'controller' in group_names"

- name: Deploy Ceph auth keys for OpenStack services for compute nodes
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0600'
  loop:
    - { src: "{{ ceph_local_files_dest_path.cinder_keyring }}", dest: "{{ ceph_keyring_file_path.cinder }}" }
    - { src: "{{ ceph_local_files_dest_path.ceph_conf }}", dest: "{{ ceph_conf_file }}" }
    - { src: "{{ ceph_local_files_dest_path.cinder_backup_keyring }}", dest: "{{ ceph_keyring_file_path.cinder_backup }}" }
  when: "'compute' in group_names"
