---
- name: Ensure Cinder volume type for Ceph
  openstack.cloud.volume_type:
    name: ceph
    is_public: true
    extra_specs:                     # ← 改成这个
      volume_backend_name: ceph
    state: present
  when: "'controller' in group_names"
