# SPDX-License-Identifier: MIT-0
---
# tasks file for roles/dns_server
# 检查服务器之前是否运行过成功过该剧本，运行过就直接跳过，如果需要重新运行，那么你要删除标记文件
- name: Check if the tasks has been running
  tags:
    - install
    - check_mark_file
  when: "'dns_server' in group_names"
  block:
    - name: Ensure Mark Directory Exists
      ansible.builtin.file:
        path: "{{ dns_server_mark_dir_path }}"
        state: directory
        mode: '0755'

    - name: Check if dns_server tasks have been run
      ansible.builtin.stat:
        name: "{{ dns_server_success_mark_file_path }}"
      register: dns_server_mark_file

    - name: Skip if dns_server tasks have been run
      ansible.builtin.meta: end_role
      when: dns_server_mark_file.stat.exists

- name: Install DNS Server Packages
  ansible.builtin.import_tasks: install_packages.yml
  tags:
    - install
  when: "'dns_server' in group_names"

- name: Deploy DNS Server Configuration Files
  ansible.builtin.import_tasks: deploy_conf_file.yml
  tags:
    - install
    - config
  when: "'dns_server' in group_names"

- name: Configure firewall for DNS Server
  ansible.builtin.import_tasks: configrue_firewalld.yml
  tags:
    - install
    - configure_DNS_Server_firewall
  when: "'dns_server' in group_names"

- name: Ensure DNS Service is started and enabled
  ansible.builtin.import_tasks: ensure_service_running.yml
  tags:
    - install
    - ensure_running
  when: "'dns_server' in group_names"

- name: Configure DNS clients to use the DNS Server
  ansible.builtin.import_tasks: configure_clients_use_local_dns.yml
  tags:
    - install
    - configure_dns_clients
  when: "'dns_clients' in group_names"

- name: Create mark file to indicate dns_server deploy tasks have been run
  ansible.builtin.file:
    path: "{{ dns_server_success_mark_file_path }}"
    state: touch
    mode: '0644'
  when: "'dns_server' in group_names"
  tags:
    - install
    - create_mark_file
