# SPDX-License-Identifier: MIT-0
---
# tasks file for roles/dns_server
- name: Check if dns server is installed and running
  block:
    - name: Gather facts of installed packages
      ansible.builtin.package_facts:
        manager: auto

    - name: Gather facts of running services
      ansible.builtin.service_facts:

    - name: Check if dns server is installed
      ansible.builtin.debug:
        msg: |
          Unbound安装状态
          已安装：{{ "'unbound' in ansible_facts.packages" }}
          版本：{{ ansible_facts.packages.unbound[0].version if 'unbound' in ansible_facts.packages else '未安装' }}

    - name: Check if Unbound status
      ansible.builtin.debug:
        msg: |
          Unbound服务状态:
          服务存在:{{ "'unbound' in ansible_facts.services" }}
          运行状态：{{ ansible_facts.services['unbound'].status if 'unbound' in ansible_facts.services else '服务不存在' }}
          是否活跃: {{ ansible_facts.services['unbound'].state == 'running' if 'unbound' in ansible_facts.services else false }}

- name: Install DNS Server Packages(unbound)
  ansible.builtin.package:
    name: unbound
    state: present

- name: Configure Unbound DNS Server
  ansible.builtin.template:
    src: template/99-openstack-local.conf.j2
    dest: /etc/unbound/conf.d/99-openstack-local.conf
    mode: "0644"
