# SPDX-License-Identifier: MIT-0
---
# tasks file for roles/keystone
- name: Check if the tasks has been running
  when: "'keystone_servers' in group_names"
  block:
    - name: Ensure Mark Directory Exists
      ansible.builtin.file:
        path: "{{ keystone_mark_dir_path }}"
        state: directory
        mode: '0755'

    - name: Check if keystone tasks have been run
      ansible.builtin.stat:
        name: "{{ keystone_mark_files_path.success }}"
      register: keystone_mark_file

    - name: Skip if keystone tasks have been run
      ansible.builtin.meta: end_role
      when: keystone_mark_file.stat.exists

- name: Create keystone database in MariaDB
  ansible.builtin.import_tasks: create_keystone_db.yml
  tags:
    - install
    - create_keystone_db
  when: "'keystone_servers' in group_names"

- name: Install Keystone Packages
  ansible.builtin.import_tasks: install_packages.yml
  tags:
    - install
  when: "'keystone_servers' in group_names"

- name: Deploy Keystone configuration file
  ansible.builtin.import_tasks: deploy_keystone_conf_file.yml
  tags:
    - install
    - configure_keystone
  when: "'keystone_servers' in group_names"

- name: Sync Keystone Database
  ansible.builtin.import_tasks: sync_keystone_db.yml
  tags:
    - install
    - sync_keystone_db
  when: "'keystone_servers' in group_names"

- name: Keystone key Initialization
  ansible.builtin.import_tasks: keystone_key_init.yml
  tags:
    - install
    - initialize_keystone
  when: "'keystone_servers' in group_names"

- name: Keystone bootstrap inialization
  ansible.builtin.import_tasks: keystone_bootstrap_init.yml
  tags:
    - install
    - bootstrap_keystone
  when: "'keystone_servers' in group_names"

- name: Configure Keystone Apache HTTPD conf file
  ansible.builtin.import_tasks: deploy_keystone_httpd_conf_file.yml
  tags:
    - install
    - configure_keystone_apache
  when: "'keystone_servers' in group_names"

- name: Make Keystone Apache HTTPD conf softlink
  ansible.builtin.import_tasks: make_soft_link.yml
  tags:
    - install
    - make_keystone_apache_softlink
  when: "'keystone_servers' in group_names"

- name: Ensure Apache HTTPD service is started, enabled and apply changes
  ansible.builtin.import_tasks: ensure_httpd_apply_changes.yml
  tags:
    - install
    - ensure_httpd_apply_changes
  when: "'keystone_servers' in group_names"

- name: Configure KeyStone Admin Env
  ansible.builtin.import_tasks: config_keystone_admin_env.yml
  tags:
    - install
    - configure_keystone_admin_env
  when: "'keystone_servers' in group_names"

- name: Create Default example project and domain
  ansible.builtin.import_tasks: create_project_and_domain.yml
  tags:
    - install
    - create_default_example_project_domain
  when: "'keystone_servers' in group_names"

- name: Create mark file to indicate Keystone tasks have been run
  ansible.builtin.file:
    path: "{{ keystone_mark_files_path.success }}"
    state: touch
    mode: '0644'
  when: "'keystone_servers' in group_names"
