---
- name: Create Nova's service user,role,endpoints,and project
  when: "'controller' in group_names"
  block:
    - name: Create Nova's service user in default domain
      openstack.cloud.identity_user:
        name: nova
        domain: default
        password: "{{ nova_openstack_service_password.nova }}"
        state: present

    - name: Assign nova role to nova service user
      openstack.cloud.role_assignment:
        project: service
        role: admin
        user: nova
        state: present

    - name: Create Nova's service entity
      openstack.cloud.catalog_service:
        name: nova
        description: "OpenStack Compute Service"
        service_type: compute
        state: present

    - name: Create Nova's service endpoints
      openstack.cloud.endpoint:
        service: nova
        endpoint_interface: "{{ item.endpoint_interface }}"
        url: "{{ item.url }}"
        region: "{{ nova_region }}"
        state: present
      loop:
        - { endpoint_interface: public, url: "http://{{ hostvars[groups['controller'][0]].inventory_hostname }}:8774/v2.1" }
        - { endpoint_interface: admin, url: "http://{{ hostvars[groups['controller'][0]].inventory_hostname }}:8774/v2.1" }
        - { endpoint_interface: internal, url: "http://{{ hostvars[groups['controller'][0]].inventory_hostname }}:8774/v2.1" }
