# SPDX-License-Identifier: MIT-0
---
# tasks file for roles/nova
- name: Check if the tasks has been running
  when: "'controller' in group_names"
  block:
    - name: Ensure Mark Directory Exists
      ansible.builtin.file:
        path: "{{ nova_mark_dir_path }}"
        state: directory
        mode: '0755'

    - name: Check if placement tasks have been run
      ansible.builtin.stat:
        name: "{{ nova_mark_files_path.controller_success }}"
      register: nova_success_mark_file

    - name: Skip if nova tasks have been run
      ansible.builtin.meta: end_role
      when: nova_success_mark_file.stat.exists

- name: Check if the tasks has been running
  when: "'compute' in group_names"
  block:
    - name: Ensure Mark Directory Exists
      ansible.builtin.file:
        path: "{{ nova_mark_dir_path }}"
        state: directory
        mode: '0755'

    - name: Check if placement tasks have been run
      ansible.builtin.stat:
        name: "{{ nova_mark_files_path.compute_success }}"
      register: nova_success_mark_file

    - name: Skip if nova tasks have been run
      ansible.builtin.meta: end_role
      when: nova_success_mark_file.stat.exists

- name: Controller node tasks
  when: "'controller' in group_names"
  block:
    - name: Create Nova database and user
      ansible.builtin.import_tasks: create_nova_db.yml
      tags: create_nova_db

    - name: Create Nova service user,role,endpoints,and project
      ansible.builtin.import_tasks: create_nova_service.yml
      tags: create_nova_service_user_role_endpoints_and_project

    - name: Install Nova Packages
      ansible.builtin.import_tasks: install_packages.yml
      tags: install_nova_packages_controller

    - name: Deploy Nova Configuration Files
      ansible.builtin.import_tasks: deploy_nova_conf_file.yml
      tags: deploy_nova_conf_files

    - name: Sync Nova Database
      ansible.builtin.import_tasks: configure_nova_db.yml
      tags: sync_nova_db

    - name: Verify results
      ansible.builtin.import_tasks: verify_result.yml
      tags: verify_results

    - name: Ensure Nova Services are started
      ansible.builtin.import_tasks: ensure_nova_services_running.yml
      tags: ensure_nova_services_restarted

    - name: Create mark file to indicate the nova controller has been configured
      ansible.builtin.file:
        path: "{{ nova_mark_files_path.controller_success }}"
        state: touch
        mode: '0644'

- name: Compute Node Tasks
  when: "'compute' in group_names"
  block:
    - name: Install nova packages
      ansible.builtin.import_tasks: install_packages.yml
      tags: install_nova_compute_packages

    - name: Deploy nova compute configuration files
      ansible.builtin.import_tasks: deploy_nova_conf_file.yml
      tags: deploy_nova_compute_conf_files

    - name: Ensure libvirtd is running and enabled
      ansible.builtin.import_tasks: ensure_libvirtd_running.yml
      tags: ensure_libvirtd_running

    - name: Ensure nova-compute service is started
      ansible.builtin.import_tasks: ensure_nova_services_running.yml
      tags: ensure_nova_compute_service_running

    - name: Create mark file to indcate nova compute tasks have been run
      ansible.builtin.file:
        path: "{{ nova_mark_files_path.compute_success }}"
        state: touch
        mode: '0644'
